# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsField',
            fields=[
                ('setting_key', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
