# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_imagelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelogo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
